### ISSUE TITLE
Remove build.gradle ?

### ISSUE THREAD

**Issue by Cervator** [DestinationSol/warp#1]
I figure this repo started out with one before we did the usual Gradle magic. Now modules get the template `build.gradle` copied in when they're fetched via `groovyw` and in fact the one in this repo is out of date. Unless there's anything special left about it I believe it can be deleted outright - just need to make sure any existing local workspaces get clean copies of the template file into all present local module dirs :-)

**Comment by BenjaminAmos** [comment]
There's nothing special about the `build.gradle` in this repostiory, it's just a left-over from when I first created the module. I'll remove the file.
