### ISSUE TITLE
Add hotkey to open "Research" menu

### ISSUE THREAD

**Issue by BenjaminAmos** [DestinationSol/warp#4]
There is currently no hotkey assigned to the research menu button, unlike most of the other in-game buttons.

Maybe assign the `R` key to open the research menu?

**Comment by DOD8495Gym** [comment]
Sorry for being technical about this, but would the Shift key be required to activate the number sign? It's just the number three otherwise.

**Comment by BenjaminAmos** [comment]
I plan for the hotkey to be `r` for ***R***esearch, rather than `Shift+r` or `Shift+3`. It would be the `r` key on the keyboard alone that you would need to press.

Later-on, it should become possible to change the key binding via the main menu but there isn't any code present that allows for modules to do that right now.

**Comment by DOD8495Gym** [comment]
Oh! I misread that as the number sign! So yes, the "R" key seems a logical choice to me. Sorry for my confusing comment.
R r #
Pity I can't get a new prescription for my glasses. The abov line is just me comparing the different characters on the keyboard. No need to pay any attention to it.
